# Basic
title: HeBao
subtitle: CQUST
welcome_message:
description: blog
creator: 

url: "http://hebaochina.top"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: HeBao
    # duoshuo: 
    
# Social
social:
    weibo: 何宝美好回忆
    github: hebao123
    twitter: hebao
    gplus: 
    mail: 879815165@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
